/**
 * Hindi (`hi-IN`) string bundle — Foundation §17 launch locale.
 * Key set mirrors `en.ts` exactly; a missing key falls back to English.
 */
import type { LocaleBundle } from "../localization.types";

export const hiINBundle: LocaleBundle = {
  locale: "hi-IN",
  version: "1.0.0",
  strings: {
    "common.app.name": "StreamFlow",
    "common.app.tagline": "साथ देखें, एक ही समय पर।",
    "common.action.retry": "फिर से कोशिश करें",
    "common.action.go_home": "होम पर जाएँ",
    "common.action.dismiss": "बंद करें",
    "common.state.loading": "लोड हो रहा है",

    "settings.language.label": "भाषा",
    "settings.appearance.theme.label": "थीम",
    "settings.appearance.theme.system": "सिस्टम",
    "settings.appearance.theme.light": "लाइट",
    "settings.appearance.theme.dark": "डार्क",

    "error.sys.unexpected.title": "कुछ गड़बड़ हो गई",
    "error.sys.unexpected": "एक अनपेक्षित समस्या आ गई। इसमें आपकी कोई गलती नहीं है।",
    "error.sys.route_not_found.title": "पेज नहीं मिला",
    "error.sys.route_not_found": "यह पेज मौजूद नहीं है, या इसे हटा दिया गया है।",
    "error.sys.config_invalid.title": "कॉन्फ़िगरेशन समस्या",
    "error.sys.config_invalid": "कॉन्फ़िगरेशन अमान्य होने के कारण StreamFlow शुरू नहीं हो सका।",
    "error.net.timeout": "अनुरोध में बहुत समय लग गया। अपना कनेक्शन जाँचें और फिर कोशिश करें।",
    "error.net.offline": "आप ऑफ़लाइन लग रहे हैं। कनेक्शन लौटते ही StreamFlow अपने आप जुड़ जाएगा।",
    "error.net.cancelled": "यह अनुरोध रद्द कर दिया गया।",
    "error.net.unreachable": "हम StreamFlow तक नहीं पहुँच सके। अपना कनेक्शन जाँचें और फिर कोशिश करें।",
    "error.net.bad_response": "हमें एक अनपेक्षित उत्तर मिला। कृपया फिर कोशिश करें।",
    "error.net.server_error": "StreamFlow में अभी कुछ दिक्कत है। थोड़ी देर बाद कोशिश करें।",
    // Sprint 1.9 — गतिविधि टाइमलाइन सारांश (Foundation §13).
    "activity.room_created": "आपने एक रूम बनाया।",
    "activity.room_joined": "आप एक रूम में शामिल हुए।",
    "activity.room_ended": "एक वॉच सेशन समाप्त हुआ।",
    "activity.invite_sent": "आपने एक आमंत्रण भेजा।",
    "activity.invite_accepted": "एक आमंत्रण स्वीकार किया गया।",
    "activity.voice_joined": "आप वॉइस चैट में शामिल हुए।",
    // Sprint 1.6 — साझा डोमेन त्रुटि वर्गीकरण (Foundation §16.1).
    "error.sys.invalid_input": "यह अनुरोध मान्य नहीं था, इसलिए कुछ नहीं बदला।",
    "error.sys.service_unavailable": "StreamFlow का यह हिस्सा अभी तैयार नहीं है। कृपया फिर कोशिश करें।",
    "error.sys.rate_limited": "आपने यह बहुत बार किया है। कृपया थोड़ा रुकें।",
    "error.room.capacity_exceeded": "यह रूम भर चुका है।",
    "error.room.invalid_transition": "यह रूम उस स्थिति में नहीं जा सकता।",
    "error.room.not_active": "यह रूम अभी सक्रिय नहीं है।",
    "error.room.not_found": "वह रूम नहीं मिला।",
    "error.room.forbidden": "यह केवल रूम होस्ट कर सकता है।",
    "error.room.already_member": "आप पहले से इस रूम में हैं।",
    "error.room.member_not_found": "वह व्यक्ति इस रूम में नहीं है।",
    "error.invite.not_found": "वह आमंत्रण नहीं मिला।",
    "error.invite.expired": "यह आमंत्रण समाप्त हो चुका है।",
    "error.invite.not_pending": "इस आमंत्रण का उत्तर पहले ही दिया जा चुका है।",
    "error.sync.countdown_out_of_range": "3 से 60 सेकंड के बीच काउंटडाउन चुनें।",
    "error.sync.resync_required": "आपकी घड़ियाँ बहुत अलग हैं। शुरू करने से पहले री-सिंक करें।",
    "error.voice.session_not_active": "इस रूम में वॉइस चैट सक्रिय नहीं है।",
    "error.provider.capability_unsupported": "यह सेवा वह क्रिया समर्थित नहीं करती।",
    "error.compliance.action_blocked": "StreamFlow इस सेवा के साथ यह नहीं कर सकता।",
    "error.net.request_failed": "यह अनुरोध पूरा नहीं हो सका। कृपया फिर कोशिश करें।",
    "error.sys.persistence_unavailable": "StreamFlow अभी आपके डेटा तक नहीं पहुँच पा रहा। थोड़ी देर बाद कोशिश करें।",
    "error.sys.persistence_failed": "हम यह पूरा नहीं कर सके। कृपया फिर कोशिश करें।",
    "error.sys.not_found": "आप जो खोज रहे थे वह नहीं मिला।",
    "error.sys.conflict": "यह कहीं और पहले ही बदल चुका है। रिफ़्रेश करके फिर कोशिश करें।",
    "error.sys.permission_denied": "आपके पास इसकी अनुमति नहीं है।",
    "error.sys.constraint_violation": "ये विवरण सहेजे नहीं जा सके। इन्हें जाँचकर फिर कोशिश करें।",
    "error.action.retry": "फिर से कोशिश करें",
    "error.action.go_home": "होम पर जाएँ",
    "error.reference.label": "संदर्भ कोड",

    "error.auth.provider_unavailable.title": "साइन-इन अभी उपलब्ध नहीं है",
    "error.auth.provider_unavailable":
      "StreamFlow की प्रमाणीकरण संरचना तैयार है, पर अभी कोई पहचान प्रदाता जुड़ा नहीं है।",
    "error.auth.invalid_credentials.title": "विवरण मेल नहीं खाया",
    "error.auth.invalid_credentials": "अपना ईमेल और पासवर्ड जाँचें, फिर दोबारा प्रयास करें।",
    "error.auth.email_not_verified.title": "अपना ईमेल सत्यापित करें",
    "error.auth.email_not_verified": "साइन-इन पूरा करने के लिए अपना ईमेल पता सत्यापित करें।",
    "error.auth.session_expired.title": "आप साइन आउट हो गए हैं",
    "error.auth.session_expired": "आपका सत्र समाप्त हो गया। जारी रखने के लिए फिर साइन इन करें।",
    "error.auth.session_missing.title": "जारी रखने के लिए साइन इन करें",
    "error.auth.session_missing": "इस पृष्ठ के लिए साइन-इन खाता आवश्यक है।",
    "error.auth.account_suspended.title": "खाता निलंबित",
    "error.auth.account_suspended": "यह खाता अभी उपयोग नहीं किया जा सकता। सहायता से संपर्क करें।",
    "error.auth.permission_denied.title": "आपके पास पहुँच नहीं है",
    "error.auth.permission_denied": "आपके खाते को यह पृष्ठ खोलने की अनुमति नहीं है।",
    "error.auth.rate_limited.title": "बहुत अधिक प्रयास",
    "error.auth.rate_limited": "दोबारा प्रयास करने से पहले कुछ देर प्रतीक्षा करें।",
    "error.auth.sign_out_failed.title": "साइन-आउट पूरा नहीं हुआ",
    "error.auth.sign_out_failed": "हम आपको साइन आउट नहीं कर सके। कृपया दोबारा प्रयास करें।",

    "auth.sign_in.title": "StreamFlow में साइन इन करें",
    "auth.sign_in.subtitle": "अपने अपने खातों से, एक साथ और एक ही समय पर देखें।",
    "auth.sign_out.title": "साइन आउट",
    "auth.sign_out.subtitle": "आपको होम पेज पर वापस भेजा जाएगा।",
    "auth.account.title": "आपका खाता",
    "auth.account.subtitle": "प्रोफ़ाइल और प्राथमिकताएँ आगामी स्प्रिंट में आएँगी।",
    "auth.action.sign_in": "साइन इन",
    "auth.action.sign_out": "साइन आउट",
    "auth.action.reset_password": "अपना पासवर्ड रीसेट करें",
    "auth.action.resend_verification": "सत्यापन ईमेल दोबारा भेजें",
    "auth.state.checking_session": "आपका सत्र जाँचा जा रहा है",
    "auth.state.redirecting": "आपको साइन-इन पर ले जाया जा रहा है",
    "auth.status.session": "सत्र स्थिति",
    "auth.status.adapter": "पहचान अडैप्टर",

    "a11y.skip_to_content": "मुख्य सामग्री पर जाएँ",
    "a11y.main_content.label": "मुख्य सामग्री",
    "a11y.loading.announcement": "लोड हो रहा है, कृपया प्रतीक्षा करें",
    "a11y.error.announcement": "एक त्रुटि हुई",
  
    "room.waiting_room.eyebrow": "प्रतीक्षा कक्ष",
    "room.waiting_room.title": "सबको एक साथ लाया जा रहा है",
    "room.waiting_room.subtitle": "होस्ट के कहने तक कुछ शुरू नहीं होगा।",
    "room.waiting_room.region_label": "प्रतीक्षा कक्ष",
    "room.waiting_room.loading": "प्रतीक्षा कक्ष लोड हो रहा है",
    "room.status.lobby": "लॉबी में",
    "room.status.active": "देखा जा रहा है",
    "room.status.paused": "रुका हुआ",
    "room.status.ended": "समाप्त",
    "room.status.abandoned": "छोड़ा गया",
    "room.info.code": "रूम कोड",
    "room.info.occupancy": "मौजूद लोग",
    "room.info.occupancy_value": "{capacity} में से {joined}",
    "room.info.scheduled_start": "नियोजित शुरुआत",
    "room.info.updates": "अपडेट",
    "room.info.updates_live": "लाइव",
    "room.info.updates_manual": "अपडेट के लिए रिफ़्रेश करें",
    "room.members.title": "सदस्य ({count})",
    "room.members.list_label": "इस रूम के लोग",
    "room.members.empty": "अभी कोई नहीं आया है। शुरू करने के लिए रूम कोड साझा करें।",
    "room.member.you": "आप",
    "room.member.host_badge": "होस्ट",
    "room.member.ready": "तैयार",
    "room.member.not_ready": "तैयार नहीं",
    "room.member_state.invited": "आमंत्रित",
    "room.member_state.joined": "रूम में",
    "room.member_state.left": "बाहर गए",
    "room.member_state.removed": "हटाए गए",
    "room.actions.title": "आपकी जगह",
    "room.actions.join": "इस रूम में शामिल हों",
    "room.actions.join_hint": "रूम में दिखने और तैयार होने का संकेत देने के लिए शामिल हों।",
    "room.actions.leave": "रूम छोड़ें",
    "room.actions.ready_label": "मैं तैयार हूँ",
    "room.actions.ready_hint": "तैयारी होस्ट को बताती है कि आप तैयार हैं। इससे प्लेबैक शुरू नहीं होता।",
    "invite.summary.title": "लंबित आमंत्रण",
    "invite.summary.empty": "किसी आमंत्रण का उत्तर बाकी नहीं है।",
    "invite.summary.pending": "{count} उत्तर की प्रतीक्षा में।",
    "invite.summary.share_hint": "जिनके साथ देखना है उन्हें कोड {code} भेजें।",
    "error.room.not_found.title": "रूम नहीं मिला",
    "error.room.member_not_found.title": "सदस्यता नहीं मिली",
    "error.room.capacity_exceeded.title": "रूम भरा हुआ है",
    "error.room.forbidden.title": "केवल होस्ट के लिए",
    "error.room.already_member.title": "आप पहले से इस रूम में हैं",
    "error.room.not_active.title": "रूम सक्रिय नहीं है",
    "error.sys.service_unavailable.title": "अभी तैयार नहीं",
    "error.sys.persistence_unavailable.title": "आपका डेटा नहीं मिल रहा",
    "error.sys.conflict.title": "कोई पहले बदल चुका है",
  
    "room.presence.online": "ऑनलाइन",
    "room.presence.idle": "निष्क्रिय",
    "room.presence.away": "दूर",
    "room.presence.offline": "ऑफ़लाइन",
    "room.presence.last_seen": "{minutes} मिनट पहले देखा गया",
    "room.members.ready_count": "{total} में से {ready} तैयार",
    "po.banner.title": "पो आपके साथ प्रतीक्षा कर रहा है",
    "po.banner.waiting": "सबके आने तक पेड़ के नीचे विश्राम कर रहा है।",
    "po.banner.all_ready": "सब तैयार हैं — पो प्रसन्न दिख रहा है।",
    "po.banner.thinking": "मेजबान के तय करने तक पो कान लगाए बैठा है।",
    "po.banner.provider_selected": "सेवा चुन ली गई — पो आराम से बैठ गया।",

    "common.save": "सहेजें",
    "common.saving": "सहेजा जा रहा है…",

    "provider.list.label": "कहाँ देखना है, वह चुनें",
    "provider.list.empty": "आपके क्षेत्र के लिए अभी कोई सेवा उपलब्ध नहीं है।",
    "provider.list.error": "सेवाओं की सूची लोड नहीं हुई। फिर कोशिश करें।",
    "provider.list.unavailable": "सेवा चयन अभी उपलब्ध नहीं है।",
    "provider.class.supported": "समर्थित",
    "provider.class.manual_sync": "मैन्युअल सिंक",
    "provider.class.unverified": "असत्यापित",
    "provider.class.unavailable": "अनुपलब्ध",
    "provider.hint.supported": "StreamFlow इसे सबके लिए साथ में चला और रोक सकता है।",
    "provider.hint.manual_sync": "सब गिनती पर एक साथ प्ले दबाएंगे। StreamFlow प्लेयर को नियंत्रित नहीं करेगा।",
    "provider.hint.unverified": "हमने इसे अभी सत्यापित नहीं किया है। आप गिनती के साथ फिर भी साथ देख सकते हैं।",
    "provider.hint.unavailable": "इस रूम में यह सेवा अभी उपयोग नहीं हो सकती।",
    "provider.badge.default": "आपकी डिफ़ॉल्ट",
    "provider.action.favorite": "{provider} को पसंदीदा में जोड़ें",
    "provider.action.unfavorite": "{provider} को पसंदीदा से हटाएं",
    "provider.youtube.name": "YouTube",
    "provider.local_file.name": "लोकल फ़ाइल",
    "provider.netflix.name": "Netflix",
    "provider.prime_video.name": "Prime Video",
    "provider.disney_hotstar.name": "Disney+ Hotstar",
    "compliance.rationale.tos_no_automation": "इस सेवा की शर्तें स्वचालित नियंत्रण की अनुमति नहीं देतीं।",
    "compliance.rationale.public_embed_api": "सेवा के अपने सार्वजनिक एम्बेड से, आपके ही सत्र में चलता है।",
    "compliance.rationale.never_store_credentials": "StreamFlow आपके खाते की जानकारी न मांगता है, न संग्रहित करता है।",
    "compliance.rationale.user_owned_media": "आपकी अपनी डिवाइस की, आपकी अपनी फ़ाइल चलती है।",
    "compliance.rationale.no_redistribution": "वीडियो StreamFlow से होकर नहीं जाता। कुछ भी साझा नहीं किया जाता।",

    "room.setup.title": "देखने से पहले",
    "room.setup.description.host": "सेवा और गिनती की अवधि चुनें। आपके कहने तक कुछ शुरू नहीं होगा।",
    "room.setup.description.guest": "मेजबान सेवा और गिनती की अवधि चुन रहा है।",
    "room.setup.selected.label": "सेवा:",
    "room.setup.selected.none": "अभी नहीं चुनी गई",
    "room.setup.countdown.label": "गिनती की अवधि (सेकंड)",
    "room.setup.countdown.hint": "{min} से {max} सेकंड के बीच। सहेजा जाएगा — अभी कुछ शुरू नहीं होगा।",
    "room.setup.countdown.invalid": "{min} से {max} के बीच पूर्ण संख्या दर्ज करें।",
    "room.setup.countdown.readonly": "गिनती {seconds} सेकंड तक चलेगी।",
    "room.countdown.title": "गिनती",
    "room.countdown.description.host": "सब तैयार हों तो गिनती शुरू करें। शून्य पर सब एक साथ प्ले दबाएँ — StreamFlow आपके लिए नहीं दबाएगा।",
    "room.countdown.description.guest": "मेजबान गिनती शुरू करेगा। अपनी सेवा खोलकर तैयार रखें।",
    "room.countdown.state.idle": "शुरू नहीं हुई",
    "room.countdown.state.preparing": "तैयारी हो रही है",
    "room.countdown.state.counting_down": "गिनती चल रही है",
    "room.countdown.state.cancelled": "रद्द",
    "room.countdown.state.completed": "अब प्ले दबाएँ",
    "room.countdown.state.expired": "समय बीत गया",
    "room.countdown.started_by": "{host} ने शुरू की",
    "room.countdown.reason.host_cancelled": "मेजबान ने गिनती रद्द कर दी।",
    "room.countdown.reason.restarted": "मेजबान ने गिनती फिर से शुरू की।",
    "room.countdown.reason.expired": "शून्य पर कोई मौजूद नहीं था, इसलिए गिनती समाप्त कर दी गई।",
    "room.countdown.action.start": "गिनती शुरू करें",
    "room.countdown.action.cancel": "गिनती रद्द करें",
    "room.countdown.action.restart": "गिनती फिर शुरू करें",
    "room.countdown.guest_hint": "गिनती केवल मेजबान शुरू या रद्द कर सकता है।",
    "room.countdown.needs_provider": "गिनती शुरू करने से पहले सेवा चुनें।",
    "room.countdown.announce.preparing": "गिनती तैयार हो रही है",
    "room.countdown.announce.counting_down": "गिनती शुरू हुई",
    "room.countdown.announce.tick": "{seconds}",
    "room.countdown.announce.cancelled": "गिनती रद्द हुई",
    "room.countdown.announce.completed": "अब प्ले दबाएँ",
    "room.countdown.announce.expired": "गिनती समाप्त हो गई",
    "po.banner.counting": "Po आपके साथ गिन रहा है।",
    "po.banner.celebrating": "Po खुश है — साथ में प्ले दबाएँ।",
    "po.banner.cancelled": "Po फिर से शांत होकर इंतज़ार करने लगा।",
    "error.provider.capability_unsupported.title": "यह सेवा यहाँ उपयोग नहीं हो सकती",
  },
};
