/**
 * Hindi (`hi-IN`) string bundle — Foundation §17 launch locale.
 * Key set mirrors `en.ts` exactly; a missing key falls back to English.
 */
import type { LocaleBundle } from "../localization.types";

export const hiINBundle: LocaleBundle = {
  locale: "hi-IN",
  version: "1.0.0",
  strings: {
    "common.app.name": "StreamFlow",
    "common.app.tagline": "साथ देखें, एक ही समय पर।",
    "common.app.publisher": "वेडोरा विज़न द्वारा",
    "common.action.learn_more": "और जानें",

    "common.action.retry": "फिर से कोशिश करें",
    "common.action.go_home": "होम पर जाएँ",
    "common.action.dismiss": "बंद करें",
    "common.state.loading": "लोड हो रहा है",

    "settings.language.label": "भाषा",
    "settings.appearance.theme.label": "थीम",
    "settings.appearance.theme.system": "सिस्टम",
    "settings.appearance.theme.light": "लाइट",
    "settings.appearance.theme.dark": "डार्क",

    "error.sys.unexpected.title": "कुछ गड़बड़ हो गई",
    "error.sys.unexpected": "एक अनपेक्षित समस्या आ गई। इसमें आपकी कोई गलती नहीं है।",
    "error.sys.route_not_found.title": "पेज नहीं मिला",
    "error.sys.route_not_found": "यह पेज मौजूद नहीं है, या इसे हटा दिया गया है।",
    "error.sys.config_invalid.title": "कॉन्फ़िगरेशन समस्या",
    "error.sys.config_invalid": "कॉन्फ़िगरेशन अमान्य होने के कारण StreamFlow शुरू नहीं हो सका।",
    "error.net.timeout": "अनुरोध में बहुत समय लग गया। अपना कनेक्शन जाँचें और फिर कोशिश करें।",
    "error.net.offline": "आप ऑफ़लाइन लग रहे हैं। कनेक्शन लौटते ही StreamFlow अपने आप जुड़ जाएगा।",
    "error.net.cancelled": "यह अनुरोध रद्द कर दिया गया।",
    "error.net.unreachable":
      "हम StreamFlow तक नहीं पहुँच सके। अपना कनेक्शन जाँचें और फिर कोशिश करें।",
    "error.net.bad_response": "हमें एक अनपेक्षित उत्तर मिला। कृपया फिर कोशिश करें।",
    "error.net.server_error": "StreamFlow में अभी कुछ दिक्कत है। थोड़ी देर बाद कोशिश करें।",
    // Sprint 1.9 — गतिविधि टाइमलाइन सारांश (Foundation §13).
    "activity.room_created": "आपने एक रूम बनाया।",
    "activity.room_joined": "आप एक रूम में शामिल हुए।",
    "activity.room_ended": "एक वॉच सेशन समाप्त हुआ।",
    "activity.invite_sent": "आपने एक आमंत्रण भेजा।",
    "activity.invite_accepted": "एक आमंत्रण स्वीकार किया गया।",
    "activity.voice_joined": "आप वॉइस चैट में शामिल हुए।",
    // Sprint 1.6 — साझा डोमेन त्रुटि वर्गीकरण (Foundation §16.1).
    "error.sys.invalid_input": "यह अनुरोध मान्य नहीं था, इसलिए कुछ नहीं बदला।",
    "error.sys.service_unavailable":
      "StreamFlow का यह हिस्सा अभी तैयार नहीं है। कृपया फिर कोशिश करें।",
    "error.sys.rate_limited": "आपने यह बहुत बार किया है। कृपया थोड़ा रुकें।",
    "error.room.capacity_exceeded": "यह रूम भर चुका है।",
    "error.room.invalid_transition": "यह रूम उस स्थिति में नहीं जा सकता।",
    "error.room.not_active": "यह रूम अभी सक्रिय नहीं है।",
    "error.room.not_found": "वह रूम नहीं मिला।",
    "error.room.forbidden": "यह केवल रूम होस्ट कर सकता है।",
    "error.room.already_member": "आप पहले से इस रूम में हैं।",
    "error.room.member_not_found": "वह व्यक्ति इस रूम में नहीं है।",
    "error.invite.not_found": "वह आमंत्रण नहीं मिला।",
    "error.invite.expired": "यह आमंत्रण समाप्त हो चुका है।",
    "error.invite.not_pending": "इस आमंत्रण का उत्तर पहले ही दिया जा चुका है।",
    "error.sync.countdown_out_of_range": "3 से 60 सेकंड के बीच काउंटडाउन चुनें।",
    "error.sync.resync_required": "आपकी घड़ियाँ बहुत अलग हैं। शुरू करने से पहले री-सिंक करें।",
    "error.voice.session_not_active": "इस रूम में वॉइस चैट सक्रिय नहीं है।",
    "error.provider.capability_unsupported": "यह सेवा वह क्रिया समर्थित नहीं करती।",
    "error.compliance.action_blocked": "StreamFlow इस सेवा के साथ यह नहीं कर सकता।",
    "error.net.request_failed": "यह अनुरोध पूरा नहीं हो सका। कृपया फिर कोशिश करें।",
    "error.sys.persistence_unavailable":
      "StreamFlow अभी आपके डेटा तक नहीं पहुँच पा रहा। थोड़ी देर बाद कोशिश करें।",
    "error.sys.persistence_failed": "हम यह पूरा नहीं कर सके। कृपया फिर कोशिश करें।",
    "error.sys.not_found": "आप जो खोज रहे थे वह नहीं मिला।",
    "error.sys.conflict": "यह कहीं और पहले ही बदल चुका है। रिफ़्रेश करके फिर कोशिश करें।",
    "error.sys.permission_denied": "आपके पास इसकी अनुमति नहीं है।",
    "error.sys.constraint_violation": "ये विवरण सहेजे नहीं जा सके। इन्हें जाँचकर फिर कोशिश करें।",
    "error.action.retry": "फिर से कोशिश करें",
    "error.action.go_home": "होम पर जाएँ",
    "error.reference.label": "संदर्भ कोड",

    "error.auth.provider_unavailable.title": "साइन-इन अभी उपलब्ध नहीं है",
    "error.auth.provider_unavailable":
      "StreamFlow की प्रमाणीकरण संरचना तैयार है, पर अभी कोई पहचान प्रदाता जुड़ा नहीं है।",
    "error.auth.invalid_credentials.title": "विवरण मेल नहीं खाया",
    "error.auth.invalid_credentials": "अपना ईमेल और पासवर्ड जाँचें, फिर दोबारा प्रयास करें।",
    "error.auth.email_not_verified.title": "अपना ईमेल सत्यापित करें",
    "error.auth.email_not_verified": "साइन-इन पूरा करने के लिए अपना ईमेल पता सत्यापित करें।",
    "error.auth.session_expired.title": "आप साइन आउट हो गए हैं",
    "error.auth.session_expired": "आपका सत्र समाप्त हो गया। जारी रखने के लिए फिर साइन इन करें।",
    "error.auth.session_missing.title": "जारी रखने के लिए साइन इन करें",
    "error.auth.session_missing": "इस पृष्ठ के लिए साइन-इन खाता आवश्यक है।",
    "error.auth.account_suspended.title": "खाता निलंबित",
    "error.auth.account_suspended": "यह खाता अभी उपयोग नहीं किया जा सकता। सहायता से संपर्क करें।",
    "error.auth.permission_denied.title": "आपके पास पहुँच नहीं है",
    "error.auth.permission_denied": "आपके खाते को यह पृष्ठ खोलने की अनुमति नहीं है।",
    "error.auth.rate_limited.title": "बहुत अधिक प्रयास",
    "error.auth.rate_limited": "दोबारा प्रयास करने से पहले कुछ देर प्रतीक्षा करें।",
    "error.auth.sign_out_failed.title": "साइन-आउट पूरा नहीं हुआ",
    "error.auth.sign_out_failed": "हम आपको साइन आउट नहीं कर सके। कृपया दोबारा प्रयास करें।",

    "auth.sign_in.title": "StreamFlow में साइन इन करें",
    "auth.sign_in.subtitle": "अपने अपने खातों से, एक साथ और एक ही समय पर देखें।",
    "auth.sign_out.title": "साइन आउट",
    "auth.sign_out.subtitle": "आपको होम पेज पर वापस भेजा जाएगा।",
    "auth.account.title": "आपका खाता",
    "auth.account.subtitle": "प्रोफ़ाइल और प्राथमिकताएँ आगामी स्प्रिंट में आएँगी।",
    "auth.action.sign_in": "साइन इन",
    "auth.action.sign_out": "साइन आउट",
    "auth.action.reset_password": "अपना पासवर्ड रीसेट करें",
    "auth.action.resend_verification": "सत्यापन ईमेल दोबारा भेजें",
    "auth.state.checking_session": "आपका सत्र जाँचा जा रहा है",
    "auth.state.redirecting": "आपको साइन-इन पर ले जाया जा रहा है",
    "auth.status.session": "सत्र स्थिति",
    "auth.status.adapter": "पहचान अडैप्टर",

    "auth.story.headline": "जहाँ भी हों, साथ मिलकर प्ले दबाइए।",
    "auth.story.body":
      "StreamFlow सबको एक साथ गिनती देकर शुरू करवाता है और बातचीत जारी रखता है। अपने ही खाते, अपने ही ऐप — कुछ भी दोबारा स्ट्रीम नहीं होता।",
    "auth.story.point.accounts": "हर कोई अपनी ही सदस्यता पर देखता है।",
    "auth.story.point.countdown": "साझा काउंटडाउन सबको एक ही फ़्रेम पर शुरू करता है।",
    "auth.story.point.voice": "फ़िल्म चलते समय वॉइस चैट चालू रहती है।",
    "auth.legal.notice":
      "आगे बढ़कर आप सहमत होते हैं कि आप अपने ही स्ट्रीमिंग खातों का उपयोग करेंगे और हर सेवा की शर्तों का पालन करेंगे।",
    "auth.method.legend": "आप कैसे साइन इन करना चाहेंगे?",
    "auth.method.password": "पासवर्ड",
    "auth.method.magic_link": "ईमेल लिंक",
    "auth.field.email": "ईमेल पता",
    "auth.field.email.placeholder": "you@example.com",
    "auth.field.password": "पासवर्ड",
    "auth.field.display_name": "प्रदर्शित नाम",
    "auth.field.display_name.placeholder": "प्रिया",
    "auth.field.display_name.hint": "आपके कमरों में सबको यही नाम दिखेगा।",
    "auth.action.create_account": "खाता बनाएँ",
    "auth.action.send_magic_link": "मुझे साइन-इन लिंक ईमेल करें",
    "auth.action.send_reset_link": "मुझे रीसेट लिंक ईमेल करें",
    "auth.action.back_to_sign_in": "साइन इन पर वापस",
    "auth.action.use_different_email": "दूसरा ईमेल उपयोग करें",
    "auth.action.resend_in": "आप {seconds} सेकंड में दोबारा भेज सकते हैं",
    "auth.magic_link.explainer": "पासवर्ड की ज़रूरत नहीं — हम आपको साइन-इन लिंक ईमेल करेंगे।",
    "auth.magic_link.hint": "यह लिंक एक बार काम करता है और 24 घंटे में समाप्त हो जाता है।",
    "auth.magic_link.sent": "अपना इनबॉक्स देखें। हमने {email} पर साइन-इन लिंक भेजा है।",
    "auth.reset.hint": "यदि उस पते का खाता मौजूद है, तो रीसेट लिंक भेज दिया गया है।",
    "auth.reset.sent": "रीसेट लिंक के लिए अपना इनबॉक्स देखें।",
    "auth.verify.sent": "हमने {email} पर सत्यापन लिंक भेजा है।",
    "auth.verify.hint": "खाता पूरा करने के लिए इसे इसी डिवाइस पर खोलें।",
    "auth.sign_up.have_account": "पहले से खाता है?",
    "auth.sign_up.title": "अपना StreamFlow खाता बनाएँ",
    "auth.sign_up.subtitle": "एक खाता, हर कमरा जिसे आप बनाएँ या जिसमें शामिल हों।",
    "auth.forgot_password.title": "अपना पासवर्ड रीसेट करें",
    "auth.forgot_password.subtitle": "नया पासवर्ड चुनने के लिए हम आपको लिंक ईमेल करेंगे।",
    "auth.verify.title": "अपना ईमेल सत्यापित करें",
    "auth.verify.subtitle": "एक क्लिक और आप अंदर।",

    "auth.validation.email_required": "अपना ईमेल पता दर्ज करें।",
    "auth.validation.email_invalid": "यह ईमेल पते जैसा नहीं लगता।",
    "auth.validation.password_required": "अपना पासवर्ड दर्ज करें।",
    "auth.validation.password_too_short": "पासवर्ड में कम से कम 8 अक्षर होने चाहिए।",
    "auth.validation.display_name_required": "एक प्रदर्शित नाम चुनें।",
    "auth.validation.display_name_too_short": "प्रदर्शित नाम में कम से कम 2 अक्षर होने चाहिए।",
    "auth.validation.display_name_too_long": "प्रदर्शित नाम अधिकतम 40 अक्षरों का हो सकता है।",


    "a11y.skip_to_content": "मुख्य सामग्री पर जाएँ",
    "a11y.main_content.label": "मुख्य सामग्री",
    "a11y.loading.announcement": "लोड हो रहा है, कृपया प्रतीक्षा करें",
    "a11y.error.announcement": "एक त्रुटि हुई",

    "room.waiting_room.eyebrow": "प्रतीक्षा कक्ष",
    "room.waiting_room.title": "सबको एक साथ लाया जा रहा है",
    "room.waiting_room.subtitle": "होस्ट के कहने तक कुछ शुरू नहीं होगा।",
    "room.waiting_room.region_label": "प्रतीक्षा कक्ष",
    "room.waiting_room.loading": "प्रतीक्षा कक्ष लोड हो रहा है",
    "room.status.lobby": "लॉबी में",
    "room.status.active": "देखा जा रहा है",
    "room.status.paused": "रुका हुआ",
    "room.status.ended": "समाप्त",
    "room.status.abandoned": "छोड़ा गया",
    "room.info.code": "रूम कोड",
    "room.info.occupancy": "मौजूद लोग",
    "room.info.occupancy_value": "{capacity} में से {joined}",
    "room.info.scheduled_start": "नियोजित शुरुआत",
    "room.info.updates": "अपडेट",
    "room.info.updates_live": "लाइव",
    "room.info.updates_manual": "अपडेट के लिए रिफ़्रेश करें",
    "room.members.title": "सदस्य ({count})",
    "room.members.list_label": "इस रूम के लोग",
    "room.members.empty": "अभी कोई नहीं आया है। शुरू करने के लिए रूम कोड साझा करें।",
    "room.member.you": "आप",
    "room.member.host_badge": "होस्ट",
    "room.member.ready": "तैयार",
    "room.member.not_ready": "तैयार नहीं",
    "room.member_state.invited": "आमंत्रित",
    "room.member_state.joined": "रूम में",
    "room.member_state.left": "बाहर गए",
    "room.member_state.removed": "हटाए गए",
    "room.actions.title": "आपकी जगह",
    "room.actions.join": "इस रूम में शामिल हों",
    "room.actions.join_hint": "रूम में दिखने और तैयार होने का संकेत देने के लिए शामिल हों।",
    "room.actions.leave": "रूम छोड़ें",
    "room.actions.ready_label": "मैं तैयार हूँ",
    "room.actions.ready_hint":
      "तैयारी होस्ट को बताती है कि आप तैयार हैं। इससे प्लेबैक शुरू नहीं होता।",
    "invite.summary.title": "लंबित आमंत्रण",
    "invite.summary.empty": "किसी आमंत्रण का उत्तर बाकी नहीं है।",
    "invite.summary.pending": "{count} उत्तर की प्रतीक्षा में।",
    "invite.summary.share_hint": "जिनके साथ देखना है उन्हें कोड {code} भेजें।",
    "error.room.not_found.title": "रूम नहीं मिला",
    "error.room.member_not_found.title": "सदस्यता नहीं मिली",
    "error.room.capacity_exceeded.title": "रूम भरा हुआ है",
    "error.room.forbidden.title": "केवल होस्ट के लिए",
    "error.room.already_member.title": "आप पहले से इस रूम में हैं",
    "error.room.not_active.title": "रूम सक्रिय नहीं है",
    "error.sys.service_unavailable.title": "अभी तैयार नहीं",
    "error.sys.persistence_unavailable.title": "आपका डेटा नहीं मिल रहा",
    "error.sys.conflict.title": "कोई पहले बदल चुका है",

    "room.presence.online": "ऑनलाइन",
    "room.presence.idle": "निष्क्रिय",
    "room.presence.away": "दूर",
    "room.presence.offline": "ऑफ़लाइन",
    "room.presence.last_seen": "{minutes} मिनट पहले देखा गया",
    "room.members.ready_count": "{total} में से {ready} तैयार",
    "po.banner.title": "पो आपके साथ प्रतीक्षा कर रहा है",
    "po.banner.waiting": "सबके आने तक पेड़ के नीचे विश्राम कर रहा है।",
    "po.banner.all_ready": "सब तैयार हैं — पो प्रसन्न दिख रहा है।",
    "po.banner.thinking": "मेजबान के तय करने तक पो कान लगाए बैठा है।",
    "po.banner.provider_selected": "सेवा चुन ली गई — पो आराम से बैठ गया।",

    "common.save": "सहेजें",
    "common.saving": "सहेजा जा रहा है…",

    "provider.list.label": "कहाँ देखना है, वह चुनें",
    "provider.list.empty": "आपके क्षेत्र के लिए अभी कोई सेवा उपलब्ध नहीं है।",
    "provider.list.error": "सेवाओं की सूची लोड नहीं हुई। फिर कोशिश करें।",
    "provider.list.unavailable": "सेवा चयन अभी उपलब्ध नहीं है।",
    "provider.class.supported": "समर्थित",
    "provider.class.manual_sync": "मैन्युअल सिंक",
    "provider.class.unverified": "असत्यापित",
    "provider.class.unavailable": "अनुपलब्ध",
    "provider.hint.supported": "StreamFlow इसे सबके लिए साथ में चला और रोक सकता है।",
    "provider.hint.manual_sync":
      "सब गिनती पर एक साथ प्ले दबाएंगे। StreamFlow प्लेयर को नियंत्रित नहीं करेगा।",
    "provider.hint.unverified":
      "हमने इसे अभी सत्यापित नहीं किया है। आप गिनती के साथ फिर भी साथ देख सकते हैं।",
    "provider.hint.unavailable": "इस रूम में यह सेवा अभी उपयोग नहीं हो सकती।",
    "provider.badge.default": "आपकी डिफ़ॉल्ट",
    "provider.action.favorite": "{provider} को पसंदीदा में जोड़ें",
    "provider.action.unfavorite": "{provider} को पसंदीदा से हटाएं",
    "provider.youtube.name": "YouTube",
    "provider.local_file.name": "लोकल फ़ाइल",
    "provider.netflix.name": "Netflix",
    "provider.prime_video.name": "Prime Video",
    "provider.disney_hotstar.name": "Disney+ Hotstar",
    "compliance.rationale.tos_no_automation":
      "इस सेवा की शर्तें स्वचालित नियंत्रण की अनुमति नहीं देतीं।",
    "compliance.rationale.public_embed_api":
      "सेवा के अपने सार्वजनिक एम्बेड से, आपके ही सत्र में चलता है।",
    "compliance.rationale.never_store_credentials":
      "StreamFlow आपके खाते की जानकारी न मांगता है, न संग्रहित करता है।",
    "compliance.rationale.user_owned_media": "आपकी अपनी डिवाइस की, आपकी अपनी फ़ाइल चलती है।",
    "compliance.rationale.no_redistribution":
      "वीडियो StreamFlow से होकर नहीं जाता। कुछ भी साझा नहीं किया जाता।",

    "room.setup.title": "देखने से पहले",
    "room.setup.description.host": "सेवा और गिनती की अवधि चुनें। आपके कहने तक कुछ शुरू नहीं होगा।",
    "room.setup.description.guest": "मेजबान सेवा और गिनती की अवधि चुन रहा है।",
    "room.setup.selected.label": "सेवा:",
    "room.setup.selected.none": "अभी नहीं चुनी गई",
    "room.setup.countdown.label": "गिनती की अवधि (सेकंड)",
    "room.setup.countdown.hint":
      "{min} से {max} सेकंड के बीच। सहेजा जाएगा — अभी कुछ शुरू नहीं होगा।",
    "room.setup.countdown.invalid": "{min} से {max} के बीच पूर्ण संख्या दर्ज करें।",
    "room.setup.countdown.readonly": "गिनती {seconds} सेकंड तक चलेगी।",
    "room.countdown.title": "गिनती",
    "room.countdown.description.host":
      "सब तैयार हों तो गिनती शुरू करें। शून्य पर सब एक साथ प्ले दबाएँ — StreamFlow आपके लिए नहीं दबाएगा।",
    "room.countdown.description.guest": "मेजबान गिनती शुरू करेगा। अपनी सेवा खोलकर तैयार रखें।",
    "room.countdown.state.idle": "शुरू नहीं हुई",
    "room.countdown.state.preparing": "तैयारी हो रही है",
    "room.countdown.state.counting_down": "गिनती चल रही है",
    "room.countdown.state.cancelled": "रद्द",
    "room.countdown.state.completed": "अब प्ले दबाएँ",
    "room.countdown.state.expired": "समय बीत गया",
    "room.countdown.started_by": "{host} ने शुरू की",
    "room.countdown.reason.host_cancelled": "मेजबान ने गिनती रद्द कर दी।",
    "room.countdown.reason.restarted": "मेजबान ने गिनती फिर से शुरू की।",
    "room.countdown.reason.expired": "शून्य पर कोई मौजूद नहीं था, इसलिए गिनती समाप्त कर दी गई।",
    "room.countdown.action.start": "गिनती शुरू करें",
    "room.countdown.action.cancel": "गिनती रद्द करें",
    "room.countdown.action.restart": "गिनती फिर शुरू करें",
    "room.countdown.guest_hint": "गिनती केवल मेजबान शुरू या रद्द कर सकता है।",
    "room.countdown.needs_provider": "गिनती शुरू करने से पहले सेवा चुनें।",
    "room.countdown.announce.preparing": "गिनती तैयार हो रही है",
    "room.countdown.announce.counting_down": "गिनती शुरू हुई",
    "room.countdown.announce.tick": "{seconds}",
    "room.countdown.announce.cancelled": "गिनती रद्द हुई",
    "room.countdown.announce.completed": "अब प्ले दबाएँ",
    "room.countdown.announce.expired": "गिनती समाप्त हो गई",
    "po.banner.counting": "Po आपके साथ गिन रहा है।",
    "po.banner.celebrating": "Po खुश है — साथ में प्ले दबाएँ।",
    "po.banner.cancelled": "Po फिर से शांत होकर इंतज़ार करने लगा।",
    "po.banner.playback_ready": "पो खड़ा हो गया — रूम देखने के लिए तैयार है।",
    "po.banner.observing": "पो घड़ियों को स्थिर होते देख रहा है।",
    "po.banner.concerned": "पो धैर्य से प्रतीक्षा कर रहा है — कोई अब भी पीछे है।",
    "po.banner.relieved": "पो ने राहत की सांस ली — कमरा फिर से एक लय में है।",
    "common.yes": "हाँ",
    "common.no": "नहीं",
    "po.banner.encouraging": "पो शांति से प्रतीक्षा कर रहा है — कमरे को बस एक पल चाहिए।",
    "room.playback_sync.status.playback_ready": "प्लेबैक तैयार",
    "room.playback_sync.status.synchronization_ready": "सिंक्रनाइज़ेशन तैयार",
    "room.playback_sync.status.waiting_for_manual_play":
      "सभी के अपने ऐप में प्ले दबाने की प्रतीक्षा है।",
    "room.playback_sync.status.waiting_for_resync": "साथ देखने से पहले री-सिंक की प्रतीक्षा है।",
    "room.playback_sync.decision.stay_synchronized": "कमरा एक लय में है।",
    "room.playback_sync.decision.recommend_resync": "री-सिंक की सलाह दी जाती है।",
    "room.playback_sync.decision.require_resync": "साथ जारी रखने से पहले री-सिंक आवश्यक है।",
    "room.playback_sync.decision.waiting": "कमरे के स्थिर होने की प्रतीक्षा है।",
    "room.playback_sync.decision.recovering": "कमरा फिर से लय में आ रहा है।",
    "room.playback_sync.correction.soft": "एक छोटा समायोजन कमरे को साथ ले आएगा।",
    "room.playback_sync.correction.hard": "कमरे को साथ लाने के लिए पूरा री-सिंक चाहिए होगा।",
    "room.room_sync.title": "कमरे का सिंक्रनाइज़ेशन",
    "room.room_sync.description":
      "सबकी घड़ियाँ कितनी मिलती हैं। कमरा हमेशा सबसे कमज़ोर प्रतिभागी को दर्शाता है।",
    "room.room_sync.count.ready": "तैयार",
    "room.room_sync.count.synced": "सिंक",
    "room.room_sync.count.waiting": "प्रतीक्षारत",
    "room.room_sync.count.of": " / {total}",
    "room.room_sync.block.resync_required":
      "काउंटडाउन रुका है: कम से कम एक व्यक्ति की घड़ी बहुत अलग है। उन्हें दोबारा माप लेने को कहें।",
    "room.room_sync.block.no_participants":
      "काउंटडाउन रुका है: अभी कोई कमरे में शामिल नहीं हुआ है।",
    "room.room_sync.block.participant_advisory":
      "कोई अब भी पीछे है। होस्ट अभी काउंटडाउन शुरू नहीं कर सकता।",
    "room.room_sync.advisory.warning":
      "घड़ियाँ थोड़ी अलग हैं। काउंटडाउन शुरू हो सकता है, पर थोड़ा अंतर रहेगा।",
    "room.room_sync.no_playback_notice":
      "StreamFlow केवल तैयारी का समन्वय करता है; यह आपका प्लेयर कभी नियंत्रित नहीं करता।",
    "room.sync.announce.room_health_changed": "कमरे का सिंक्रनाइज़ेशन: {health}।",
    "room.sync.title": "सिंक स्थिति",
    "room.sync.description":
      "इस डिवाइस की घड़ी रूम की घड़ी से कितनी मेल खाती है। यह केवल मापा जाता है, सुधारा नहीं जाता।",
    "room.sync.health.excellent": "उत्कृष्ट",
    "room.sync.health.good": "अच्छा",
    "room.sync.health.warning": "चेतावनी",
    "room.sync.health.resync_required": "फिर से सिंक आवश्यक",
    "room.sync.health.unknown": "मापा जा रहा है…",
    "room.sync.metric.offset": "घड़ी का अंतर",
    "room.sync.metric.latency": "लेटेंसी",
    "room.sync.metric.confidence": "विश्वास",
    "room.sync.metric.milliseconds": "{value} मिलीसेकंड",
    "room.sync.metric.percent": "{value}%",
    "room.sync.measuring": "पहली माप ली जा रही है…",
    "room.sync.measuring_action": "मापा जा रहा है…",
    "room.sync.measure_action": "फिर से मापें",
    "room.sync.unavailable": "इस डिवाइस पर सिंक उपलब्ध नहीं है।",
    "room.sync.resync_hint": "घड़ियाँ बहुत अलग हैं। काउंटडाउन शुरू करने से पहले फिर से मापें।",
    "room.sync.no_correction_notice":
      "StreamFlow सिंक स्थिति बताता है; वह आपका प्लेबैक कभी नहीं बदलता।",
    "room.sync.announce.health_changed": "सिंक स्थिति: {health}।",
    "room.playback.title": "देखने के लिए तैयार",
    "room.playback.description":
      "सभी तैयार हैं। अपने ऐप में प्ले दबाएं — StreamFlow आपका प्लेयर कभी नहीं चलाता।",
    "room.playback.state.idle": "अभी तैयार नहीं",
    "room.playback.state.queued": "रूम तैयार हो रहा है",
    "room.playback.state.ready": "तैयार — प्ले दबाएं",
    "room.playback.state.playing": "चल रहा है",
    "room.playback.state.paused": "रुका हुआ",
    "room.playback.state.seeking": "नए स्थान पर जा रहे हैं",
    "room.playback.state.completed": "समाप्त",
    "room.playback.state.error": "कुछ गलत हो गया",
    "room.playback.arming": "रूम तैयार किया जा रहा है…",
    "room.playback.press_play_hint": "अपने खाते में अभी प्ले दबाएं।",
    "room.playback.owner": "{owner} रूम को एक साथ रख रहे हैं।",
    "room.playback.no_control_notice":
      "StreamFlow आपकी स्ट्रीमिंग सेवा को नियंत्रित नहीं करता और न ही आपका साइन-इन संग्रहीत करता है।",
    "room.playback.announce.countdown_complete": "काउंटडाउन पूरा हुआ।",
    "room.playback.announce.waiting_for_playback": "प्लेबैक की प्रतीक्षा है।",
    "error.provider.capability_unsupported.title": "यह सेवा यहाँ उपयोग नहीं हो सकती",
    // Sprint 2.8 — provider launch and manual-sync guidance.
    "provider.launch.class.supported": "समर्थित",
    "provider.launch.class.manual_sync": "मैनुअल सिंक",
    "provider.launch.class.deep_link": "बाहर खुलेगा",
    "provider.launch.class.unsupported": "उपलब्ध नहीं",
    "provider.launch.target.app": "ऐप खोलें",
    "provider.launch.target.web": "ब्राउज़र में खोलें",
    "provider.launch.target.homepage": "प्रोवाइडर खोलें",
    "provider.launch.target.store": "ऐप डाउनलोड करें",
    "provider.launch.status.not_launched": "आपने अभी प्रोवाइडर नहीं खोला है।",
    "provider.launch.status.launching": "आपका प्रोवाइडर खोला जा रहा है…",
    "provider.launch.status.launched": "प्रोवाइडर खुल गया। काउंटडाउन के लिए यहाँ लौटें।",
    "provider.launch.status.failed": "कुछ नहीं खुला। ब्राउज़र विकल्प आज़माएँ।",
    "provider.launch.refusal.compliance_blocked": "यह प्रोवाइडर StreamFlow से नहीं खोला जा सकता।",
    "provider.launch.refusal.provider_unavailable":
      "यह प्रोवाइडर अभी आपके क्षेत्र में उपलब्ध नहीं है।",
    "provider.launch.refusal.missing_content_reference": "होस्ट ने अभी कोई शीर्षक नहीं चुना है।",
    "provider.launch.refusal.no_known_destination": "StreamFlow को इस प्रोवाइडर का पता नहीं है।",
    "provider.launch.refusal.local_media": "अपनी फ़ाइल अपने प्लेयर में खोलें।",
    "provider.launch.announce.opened": "प्रोवाइडर नई विंडो में खुल गया।",
    "provider.launch.announce.failed": "प्रोवाइडर नहीं खुला।",
    "provider.guidance.heading.supported": "काउंटडाउन से पहले",
    "provider.guidance.heading.manual_sync": "मैनुअल सिंक के चरण",
    "provider.guidance.heading.deep_link": "तैयारी करें",
    "provider.guidance.heading.unsupported": "यह क्यों उपलब्ध नहीं है",
    "provider.guidance.summary.supported": "शून्य पर सब एक साथ प्ले दबाते हैं।",
    "provider.guidance.summary.manual_sync":
      "StreamFlow गिनती करता है; प्ले आप अपने ऐप में दबाते हैं।",
    "provider.guidance.summary.deep_link":
      "StreamFlow प्रोवाइडर खोलता है, फिर नियंत्रण आपको देता है।",
    "provider.guidance.summary.unsupported": "StreamFlow यह प्रोवाइडर नहीं खोलेगा।",
    "provider.guidance.unsupported.explain": "StreamFlow केवल अनुमत प्रोवाइडर से ही लिंक करता है।",
    "provider.guidance.step.open_provider": "ऊपर दिए बटन से प्रोवाइडर खोलें।",
    "provider.guidance.step.sign_in_own_account": "अपने खाते से साइन इन करें।",
    "provider.guidance.step.find_title": "होस्ट द्वारा चुना गया शीर्षक खोलें।",
    "provider.guidance.step.return_and_wait": "StreamFlow पर लौटें और काउंटडाउन का इंतज़ार करें।",
    "provider.guidance.step.press_play_on_zero": "शून्य पर अपने ऐप में प्ले दबाएँ।",
    "provider.guidance.youtube.pause_at_start": "शुरुआत में रोक कर रखें ताकि सब साथ शुरू करें।",
    "provider.guidance.netflix.skip_intro_together": "इंट्रो स्किप करने पर पहले सहमत हों।",
    "provider.guidance.prime_video.check_audio_track":
      "सुनिश्चित करें सबका ऑडियो ट्रैक एक जैसा है।",
    "provider.guidance.disney_hotstar.check_language": "सुनिश्चित करें सबने एक ही भाषा चुनी है।",
    "provider.guidance.local_file.open_your_copy": "अपनी फ़ाइल अपने सामान्य प्लेयर में खोलें।",
    "provider.guidance.local_file.confirm_same_cut": "सुनिश्चित करें सबके पास एक ही संस्करण है।",
    // Sprint 2.9 — तैयारी की पुष्टि, होस्ट सारांश और मैनुअल प्ले रिमाइंडर।
    "room.actions.member_hint": "आप रूम में हैं। अपना ऐप खोलने के बाद तैयार होने की पुष्टि करें।",
    "room.ready.title": "शुरू करने के लिए तैयार",
    "room.ready.description": "रूम को बताएं कि आप तैयार हैं। हर कोई खुद ही पुष्टि करता है।",
    "room.ready.state.not_member": "तैयारी बताने के लिए पहले रूम में शामिल हों।",
    "room.ready.state.not_ready": "आपने अभी पुष्टि नहीं की है।",
    "room.ready.state.launch_pending": "आपका प्रोवाइडर खुल रहा है…",
    "room.ready.state.waiting_for_others": "आप तैयार हैं। बाकी लोगों का इंतज़ार है।",
    "room.ready.state.everyone_ready": "सब तैयार हैं।",
    "room.ready.count": "{total} में से {ready} तैयार",
    "room.ready.action.confirm": "मैं तैयार हूँ",
    "room.ready.action.undo": "अभी तैयार नहीं हूँ",
    "room.ready.timeout_hint":
      "आप काफ़ी देर से बिना पुष्टि किए रूम में हैं। तैयार होने पर पुष्टि करें।",
    "room.ready.late_join_hint": "रूम तैयार होने के बाद कोई शामिल हुआ है। उन्हें थोड़ा समय दें।",
    "room.ready.no_control_notice": "StreamFlow सिर्फ़ समय मिलाता है; प्ले हमेशा आप खुद दबाते हैं।",
    "room.ready.block.no_participants": "अभी तक कोई रूम में शामिल नहीं हुआ।",
    "room.ready.block.no_provider": "होस्ट ने अभी कोई सेवा नहीं चुनी है।",
    "room.ready.block.not_everyone_ready": "सबकी तैयारी की पुष्टि का इंतज़ार है।",
    "room.ready.block.resync_required": "काउंटडाउन से पहले रूम को फिर से सिंक करना होगा।",
    "room.ready.announce.member_ready": "{member} तैयार हैं।",
    "room.ready.announce.everyone_ready": "सब तैयार हैं।",
    "room.ready.announce.countdown_available": "काउंटडाउन उपलब्ध है।",
    "room.ready.announce.manual_play_reminder":
      "काउंटडाउन खत्म होते ही अपने ऐप में प्ले दबाना याद रखें।",
    "room.summary.title": "रूम सारांश",
    "room.summary.description": "काउंटडाउन शुरू करने से पहले ज़रूरी सब कुछ।",
    "room.summary.members_ready": "तैयार सदस्य",
    "room.summary.members_waiting": "प्रतीक्षारत सदस्य",
    "room.summary.synchronization": "सिंक्रोनाइज़ेशन",
    "room.summary.provider": "सेवा",
    "room.summary.provider_missing": "अभी नहीं चुनी",
    "room.summary.countdown": "काउंटडाउन उपलब्ध",
    "room.summary.waiting_on": "{members} का इंतज़ार है।",
    "room.summary.timed_out": "{members} काफ़ी देर से बिना पुष्टि किए इंतज़ार में हैं।",
    "room.manual_play.before": "काउंटडाउन खत्म होने पर अपने स्ट्रीमिंग ऐप में प्ले दबाएँ।",
    "room.manual_play.now": "अब अपने ऐप में प्ले दबाएँ।",
    "po.banner.waiting_for_members": "Po शांति से इंतज़ार करता है जब तक सब तैयार हों।",
    "po.banner.someone_ready": "Po खुश हुआ — कोई और तैयार है।",
  },
};
