/**
 * Hindi (`hi-IN`) string bundle — Foundation §17 launch locale.
 * Key set mirrors `en.ts` exactly; a missing key falls back to English.
 */
import type { LocaleBundle } from "../localization.types";

export const hiINBundle: LocaleBundle = {
  locale: "hi-IN",
  version: "1.0.0",
  strings: {
    "common.app.name": "StreamFlow",
    "common.app.tagline": "साथ देखें, एक ही समय पर।",
    "common.action.retry": "फिर से कोशिश करें",
    "common.action.go_home": "होम पर जाएँ",
    "common.action.dismiss": "बंद करें",
    "common.state.loading": "लोड हो रहा है",

    "settings.language.label": "भाषा",
    "settings.appearance.theme.label": "थीम",
    "settings.appearance.theme.system": "सिस्टम",
    "settings.appearance.theme.light": "लाइट",
    "settings.appearance.theme.dark": "डार्क",

    "error.sys.unexpected.title": "कुछ गड़बड़ हो गई",
    "error.sys.unexpected": "एक अनपेक्षित समस्या आ गई। इसमें आपकी कोई गलती नहीं है।",
    "error.sys.route_not_found.title": "पेज नहीं मिला",
    "error.sys.route_not_found": "यह पेज मौजूद नहीं है, या इसे हटा दिया गया है।",
    "error.sys.config_invalid.title": "कॉन्फ़िगरेशन समस्या",
    "error.sys.config_invalid": "कॉन्फ़िगरेशन अमान्य होने के कारण StreamFlow शुरू नहीं हो सका।",
    "error.net.timeout": "अनुरोध में बहुत समय लग गया। अपना कनेक्शन जाँचें और फिर कोशिश करें।",
    "error.net.offline": "आप ऑफ़लाइन लग रहे हैं। कनेक्शन लौटते ही StreamFlow अपने आप जुड़ जाएगा।",
    "error.net.cancelled": "यह अनुरोध रद्द कर दिया गया।",
    "error.net.unreachable": "हम StreamFlow तक नहीं पहुँच सके। अपना कनेक्शन जाँचें और फिर कोशिश करें।",
    "error.net.bad_response": "हमें एक अनपेक्षित उत्तर मिला। कृपया फिर कोशिश करें।",
    "error.net.server_error": "StreamFlow में अभी कुछ दिक्कत है। थोड़ी देर बाद कोशिश करें।",
    // Sprint 1.6 — साझा डोमेन त्रुटि वर्गीकरण (Foundation §16.1).
    "error.sys.invalid_input": "यह अनुरोध मान्य नहीं था, इसलिए कुछ नहीं बदला।",
    "error.sys.service_unavailable": "StreamFlow का यह हिस्सा अभी तैयार नहीं है। कृपया फिर कोशिश करें।",
    "error.sys.rate_limited": "आपने यह बहुत बार किया है। कृपया थोड़ा रुकें।",
    "error.room.capacity_exceeded": "यह रूम भर चुका है।",
    "error.room.invalid_transition": "यह रूम उस स्थिति में नहीं जा सकता।",
    "error.room.not_active": "यह रूम अभी सक्रिय नहीं है।",
    "error.room.not_found": "वह रूम नहीं मिला।",
    "error.room.forbidden": "यह केवल रूम होस्ट कर सकता है।",
    "error.room.already_member": "आप पहले से इस रूम में हैं।",
    "error.room.member_not_found": "वह व्यक्ति इस रूम में नहीं है।",
    "error.invite.not_found": "वह आमंत्रण नहीं मिला।",
    "error.invite.expired": "यह आमंत्रण समाप्त हो चुका है।",
    "error.invite.not_pending": "इस आमंत्रण का उत्तर पहले ही दिया जा चुका है।",
    "error.sync.countdown_out_of_range": "3 से 60 सेकंड के बीच काउंटडाउन चुनें।",
    "error.sync.resync_required": "आपकी घड़ियाँ बहुत अलग हैं। शुरू करने से पहले री-सिंक करें।",
    "error.voice.session_not_active": "इस रूम में वॉइस चैट सक्रिय नहीं है।",
    "error.provider.capability_unsupported": "यह सेवा वह क्रिया समर्थित नहीं करती।",
    "error.compliance.action_blocked": "StreamFlow इस सेवा के साथ यह नहीं कर सकता।",
    "error.net.request_failed": "यह अनुरोध पूरा नहीं हो सका। कृपया फिर कोशिश करें।",
    "error.sys.persistence_unavailable": "StreamFlow अभी आपके डेटा तक नहीं पहुँच पा रहा। थोड़ी देर बाद कोशिश करें।",
    "error.sys.persistence_failed": "हम यह पूरा नहीं कर सके। कृपया फिर कोशिश करें।",
    "error.sys.not_found": "आप जो खोज रहे थे वह नहीं मिला।",
    "error.sys.conflict": "यह कहीं और पहले ही बदल चुका है। रिफ़्रेश करके फिर कोशिश करें।",
    "error.sys.permission_denied": "आपके पास इसकी अनुमति नहीं है।",
    "error.sys.constraint_violation": "ये विवरण सहेजे नहीं जा सके। इन्हें जाँचकर फिर कोशिश करें।",
    "error.action.retry": "फिर से कोशिश करें",
    "error.action.go_home": "होम पर जाएँ",
    "error.reference.label": "संदर्भ कोड",

    "error.auth.provider_unavailable.title": "साइन-इन अभी उपलब्ध नहीं है",
    "error.auth.provider_unavailable":
      "StreamFlow की प्रमाणीकरण संरचना तैयार है, पर अभी कोई पहचान प्रदाता जुड़ा नहीं है।",
    "error.auth.invalid_credentials.title": "विवरण मेल नहीं खाया",
    "error.auth.invalid_credentials": "अपना ईमेल और पासवर्ड जाँचें, फिर दोबारा प्रयास करें।",
    "error.auth.email_not_verified.title": "अपना ईमेल सत्यापित करें",
    "error.auth.email_not_verified": "साइन-इन पूरा करने के लिए अपना ईमेल पता सत्यापित करें।",
    "error.auth.session_expired.title": "आप साइन आउट हो गए हैं",
    "error.auth.session_expired": "आपका सत्र समाप्त हो गया। जारी रखने के लिए फिर साइन इन करें।",
    "error.auth.session_missing.title": "जारी रखने के लिए साइन इन करें",
    "error.auth.session_missing": "इस पृष्ठ के लिए साइन-इन खाता आवश्यक है।",
    "error.auth.account_suspended.title": "खाता निलंबित",
    "error.auth.account_suspended": "यह खाता अभी उपयोग नहीं किया जा सकता। सहायता से संपर्क करें।",
    "error.auth.permission_denied.title": "आपके पास पहुँच नहीं है",
    "error.auth.permission_denied": "आपके खाते को यह पृष्ठ खोलने की अनुमति नहीं है।",
    "error.auth.rate_limited.title": "बहुत अधिक प्रयास",
    "error.auth.rate_limited": "दोबारा प्रयास करने से पहले कुछ देर प्रतीक्षा करें।",
    "error.auth.sign_out_failed.title": "साइन-आउट पूरा नहीं हुआ",
    "error.auth.sign_out_failed": "हम आपको साइन आउट नहीं कर सके। कृपया दोबारा प्रयास करें।",

    "auth.sign_in.title": "StreamFlow में साइन इन करें",
    "auth.sign_in.subtitle": "अपने अपने खातों से, एक साथ और एक ही समय पर देखें।",
    "auth.sign_out.title": "साइन आउट",
    "auth.sign_out.subtitle": "आपको होम पेज पर वापस भेजा जाएगा।",
    "auth.account.title": "आपका खाता",
    "auth.account.subtitle": "प्रोफ़ाइल और प्राथमिकताएँ आगामी स्प्रिंट में आएँगी।",
    "auth.action.sign_in": "साइन इन",
    "auth.action.sign_out": "साइन आउट",
    "auth.action.reset_password": "अपना पासवर्ड रीसेट करें",
    "auth.action.resend_verification": "सत्यापन ईमेल दोबारा भेजें",
    "auth.state.checking_session": "आपका सत्र जाँचा जा रहा है",
    "auth.state.redirecting": "आपको साइन-इन पर ले जाया जा रहा है",
    "auth.status.session": "सत्र स्थिति",
    "auth.status.adapter": "पहचान अडैप्टर",

    "a11y.skip_to_content": "मुख्य सामग्री पर जाएँ",
    "a11y.main_content.label": "मुख्य सामग्री",
    "a11y.loading.announcement": "लोड हो रहा है, कृपया प्रतीक्षा करें",
    "a11y.error.announcement": "एक त्रुटि हुई",
  },
};
